// console.log(process.env.FLIGHTAWARE_AEROAPI_KEY);

// GET /flights/{ident}
async function getFlight(ident) {
    const response = await fetch(
        `https://aeroapi.flightaware.com/aeroapi/flights/${ident}`,
        {headers: {"x-apikey": process.env.FLIGHTAWARE_AEROAPI_KEY}},
    );
    const data = await response.json();

    const flight = data?.flights?.[0];
    // console.log("Full response:", JSON.stringify(data, null, 2));
    // console.log("ident_iata:", flight?.ident_iata);
    // console.log("ident_icao:", flight?.ident_icao);
    console.log(`https://www.flightaware.com/live/flight/${flight.ident_icao}`);
}
getFlight("LA8070");

// ---

// response.data examples

// Success
// {
//   "flights": [
//     {
//       "ident": "TAM8070",
//       "ident_icao": "TAM8070",
//       "ident_iata": "JJ8070",
//       "actual_runway_off": null,
//       "actual_runway_on": null,
//       "fa_flight_id": "TAM8070-1775969661-airline-531p",
//       "operator": "TAM",
//       "operator_icao": "TAM",
//       "operator_iata": "JJ",
//       "flight_number": "8070",
//       "registration": null,
//       "atc_ident": null,
//       "inbound_fa_flight_id": null,
//       "codeshares": [
//         "JAL5512",
//         "CCA7110",
//         "LAN8070",
//         "KAL7968",
//         "FIN4424"
//       ],
//       "codeshares_iata": [
//         "JL5512",
//         "CA7110",
//         "LA8070",
//         "KE7968",
//         "AY4424"
//       ],
//       "blocked": false,
//       "diverted": false,
//       "cancelled": false,
//       "position_only": false,
//       "origin": {
//         "code": "SBGR",
//         "code_icao": "SBGR",
//         "code_iata": "GRU",
//         "code_lid": null,
//         "timezone": "America/Sao_Paulo",
//         "name": "São Paulo-Guarulhos Int'l",
//         "city": "Sao Paulo",
//         "airport_info_url": "/airports/SBGR"
//       },
//       "destination": {
//         "code": "EDDF",
//         "code_icao": "EDDF",
//         "code_iata": "FRA",
//         "code_lid": null,
//         "timezone": "Europe/Berlin",
//         "name": "Frankfurt Int'l",
//         "city": "Frankfurt am Main",
//         "airport_info_url": "/airports/EDDF"
//       },
//       "departure_delay": 0,
//       "arrival_delay": 0,
//       "filed_ete": 40800,
//       "foresight_predictions_available": false,
//       "scheduled_out": "2026-04-15T02:45:00Z",
//       "estimated_out": "2026-04-15T02:45:00Z",
//       "actual_out": null,
//       "scheduled_off": "2026-04-15T02:55:00Z",
//       "estimated_off": "2026-04-15T02:55:00Z",
//       "actual_off": null,
//       "scheduled_on": "2026-04-15T14:15:00Z",
//       "estimated_on": "2026-04-15T14:15:00Z",
//       "actual_on": null,
//       "scheduled_in": "2026-04-15T14:25:00Z",
//       "estimated_in": "2026-04-15T14:25:00Z",
//       "actual_in": null,
//       "progress_percent": 0,
//       "status": "Scheduled",
//       "aircraft_type": "B773",
//       "route_distance": 6093,
//       "filed_airspeed": 468,
//       "filed_altitude": null,
//       "route": null,
//       "baggage_claim": null,
//       "seats_cabin_business": null,
//       "seats_cabin_coach": null,
//       "seats_cabin_first": null,
//       "gate_origin": null,
//       "gate_destination": null,
//       "terminal_origin": "3",
//       "terminal_destination": "1",
//       "type": "Airline"
//     },
//     {
//       "ident": "TAM8070",
//       "ident_icao": "TAM8070",
//       "ident_iata": "JJ8070",
//       "actual_runway_off": null,
//       "actual_runway_on": null,
//       "fa_flight_id": "TAM8070-1775884374-airline-385p",
//       "operator": "TAM",
//       "operator_icao": "TAM",
//       "operator_iata": "JJ",
//       "flight_number": "8070",
//       "registration": "PT-MUA",
//       "atc_ident": null,
//       "inbound_fa_flight_id": "TAM8073-1775890297-airline-1053p",
//       "codeshares": [
//         "JAL5512",
//         "CCA7110",
//         "LAN8070",
//         "KAL7968",
//         "FIN4424"
//       ],
//       "codeshares_iata": [
//         "JL5512",
//         "CA7110",
//         "LA8070",
//         "KE7968",
//         "AY4424"
//       ],
//       "blocked": false,
//       "diverted": false,
//       "cancelled": false,
//       "position_only": false,
//       "origin": {
//         "code": "SBGR",
//         "code_icao": "SBGR",
//         "code_iata": "GRU",
//         "code_lid": null,
//         "timezone": "America/Sao_Paulo",
//         "name": "São Paulo-Guarulhos Int'l",
//         "city": "Sao Paulo",
//         "airport_info_url": "/airports/SBGR"
//       },
//       "destination": {
//         "code": "EDDF",
//         "code_icao": "EDDF",
//         "code_iata": "FRA",
//         "code_lid": null,
//         "timezone": "Europe/Berlin",
//         "name": "Frankfurt Int'l",
//         "city": "Frankfurt am Main",
//         "airport_info_url": "/airports/EDDF"
//       },
//       "departure_delay": 0,
//       "arrival_delay": 0,
//       "filed_ete": 39720,
//       "foresight_predictions_available": false,
//       "scheduled_out": "2026-04-14T02:45:00Z",
//       "estimated_out": "2026-04-14T02:45:00Z",
//       "actual_out": null,
//       "scheduled_off": "2026-04-14T02:55:00Z",
//       "estimated_off": "2026-04-14T03:07:00Z",
//       "actual_off": null,
//       "scheduled_on": "2026-04-14T13:57:00Z",
//       "estimated_on": "2026-04-14T14:09:00Z",
//       "actual_on": null,
//       "scheduled_in": "2026-04-14T14:25:00Z",
//       "estimated_in": "2026-04-14T14:25:00Z",
//       "actual_in": null,
//       "progress_percent": 0,
//       "status": "Scheduled",
//       "aircraft_type": "B773",
//       "route_distance": 6093,
//       "filed_airspeed": 468,
//       "filed_altitude": null,
//       "route": null,
//       "baggage_claim": null,
//       "seats_cabin_business": null,
//       "seats_cabin_coach": null,
//       "seats_cabin_first": null,
//       "gate_origin": null,
//       "gate_destination": null,
//       "terminal_origin": "3",
//       "terminal_destination": "1",
//       "type": "Airline"
//     },
//     {
//       "ident": "TAM8070",
//       "ident_icao": "TAM8070",
//       "ident_iata": "JJ8070",
//       "actual_runway_off": null,
//       "actual_runway_on": null,
//       "fa_flight_id": "TAM8070-1775800507-airline-4147p",
//       "operator": "TAM",
//       "operator_icao": "TAM",
//       "operator_iata": "JJ",
//       "flight_number": "8070",
//       "registration": "PT-MUB",
//       "atc_ident": null,
//       "inbound_fa_flight_id": "TAM8073-1775803783-airline-1332p",
//       "codeshares": [
//         "JAL5512",
//         "CCA7110",
//         "LAN8070",
//         "KAL7968",
//         "FIN4424"
//       ],
//       "codeshares_iata": [
//         "JL5512",
//         "CA7110",
//         "LA8070",
//         "KE7968",
//         "AY4424"
//       ],
//       "blocked": false,
//       "diverted": false,
//       "cancelled": false,
//       "position_only": false,
//       "origin": {
//         "code": "SBGR",
//         "code_icao": "SBGR",
//         "code_iata": "GRU",
//         "code_lid": null,
//         "timezone": "America/Sao_Paulo",
//         "name": "São Paulo-Guarulhos Int'l",
//         "city": "Sao Paulo",
//         "airport_info_url": "/airports/SBGR"
//       },
//       "destination": {
//         "code": "EDDF",
//         "code_icao": "EDDF",
//         "code_iata": "FRA",
//         "code_lid": null,
//         "timezone": "Europe/Berlin",
//         "name": "Frankfurt Int'l",
//         "city": "Frankfurt am Main",
//         "airport_info_url": "/airports/EDDF"
//       },
//       "departure_delay": 0,
//       "arrival_delay": 0,
//       "filed_ete": 39720,
//       "foresight_predictions_available": false,
//       "scheduled_out": "2026-04-13T02:45:00Z",
//       "estimated_out": "2026-04-13T02:45:00Z",
//       "actual_out": null,
//       "scheduled_off": "2026-04-13T02:55:00Z",
//       "estimated_off": "2026-04-13T03:07:00Z",
//       "actual_off": null,
//       "scheduled_on": "2026-04-13T13:57:00Z",
//       "estimated_on": "2026-04-13T14:09:00Z",
//       "actual_on": null,
//       "scheduled_in": "2026-04-13T14:25:00Z",
//       "estimated_in": "2026-04-13T14:25:00Z",
//       "actual_in": null,
//       "progress_percent": 0,
//       "status": "Scheduled",
//       "aircraft_type": "B773",
//       "route_distance": 6093,
//       "filed_airspeed": 468,
//       "filed_altitude": null,
//       "route": null,
//       "baggage_claim": null,
//       "seats_cabin_business": null,
//       "seats_cabin_coach": null,
//       "seats_cabin_first": null,
//       "gate_origin": "326",
//       "gate_destination": null,
//       "terminal_origin": "3",
//       "terminal_destination": "1",
//       "type": "Airline"
//     },
//     {
//       "ident": "TAM8070",
//       "ident_icao": "TAM8070",
//       "ident_iata": "JJ8070",
//       "actual_runway_off": "10L",
//       "actual_runway_on": "25R",
//       "fa_flight_id": "TAM8070-1775715170-airline-153p",
//       "operator": "TAM",
//       "operator_icao": "TAM",
//       "operator_iata": "JJ",
//       "flight_number": "8070",
//       "registration": "PT-MUG",
//       "atc_ident": null,
//       "inbound_fa_flight_id": "TAM8147-1775715263-airline-4262p",
//       "codeshares": [
//         "JAL5512",
//         "CCA7110",
//         "LAN8070",
//         "KAL7968",
//         "FIN4424"
//       ],
//       "codeshares_iata": [
//         "JL5512",
//         "CA7110",
//         "LA8070",
//         "KE7968",
//         "AY4424"
//       ],
//       "blocked": false,
//       "diverted": false,
//       "cancelled": false,
//       "position_only": false,
//       "origin": {
//         "code": "SBGR",
//         "code_icao": "SBGR",
//         "code_iata": "GRU",
//         "code_lid": null,
//         "timezone": "America/Sao_Paulo",
//         "name": "São Paulo-Guarulhos Int'l",
//         "city": "Sao Paulo",
//         "airport_info_url": "/airports/SBGR"
//       },
//       "destination": {
//         "code": "EDDF",
//         "code_icao": "EDDF",
//         "code_iata": "FRA",
//         "code_lid": null,
//         "timezone": "Europe/Berlin",
//         "name": "Frankfurt Int'l",
//         "city": "Frankfurt am Main",
//         "airport_info_url": "/airports/EDDF"
//       },
//       "departure_delay": 2760,
//       "arrival_delay": 1020,
//       "filed_ete": 39720,
//       "foresight_predictions_available": true,
//       "scheduled_out": "2026-04-12T02:45:00Z",
//       "estimated_out": "2026-04-12T02:45:00Z",
//       "actual_out": "2026-04-12T03:31:00Z",
//       "scheduled_off": "2026-04-12T02:55:00Z",
//       "estimated_off": "2026-04-12T03:44:03Z",
//       "actual_off": "2026-04-12T03:44:03Z",
//       "scheduled_on": "2026-04-12T13:57:00Z",
//       "estimated_on": "2026-04-12T14:29:09Z",
//       "actual_on": "2026-04-12T14:29:09Z",
//       "scheduled_in": "2026-04-12T14:25:00Z",
//       "estimated_in": "2026-04-12T14:44:00Z",
//       "actual_in": "2026-04-12T14:42:00Z",
//       "progress_percent": 100,
//       "status": "Arrived / Gate Arrival",
//       "aircraft_type": "B773",
//       "route_distance": 6093,
//       "filed_airspeed": 468,
//       "filed_altitude": null,
//       "route": null,
//       "baggage_claim": null,
//       "seats_cabin_business": null,
//       "seats_cabin_coach": null,
//       "seats_cabin_first": null,
//       "gate_origin": "322",
//       "gate_destination": null,
//       "terminal_origin": "3",
//       "terminal_destination": "1",
//       "type": "Airline"
//     },
//     {
//       "ident": "TAM8070",
//       "ident_icao": "TAM8070",
//       "ident_iata": "JJ8070",
//       "actual_runway_off": "10L",
//       "actual_runway_on": "07L",
//       "fa_flight_id": "TAM8070-1775625415-airline-183p",
//       "operator": "TAM",
//       "operator_icao": "TAM",
//       "operator_iata": "JJ",
//       "flight_number": "8070",
//       "registration": "PT-MUA",
//       "atc_ident": null,
//       "inbound_fa_flight_id": "TAM8115-1775627436-airline-4868p",
//       "codeshares": [
//         "JAL5512",
//         "CCA7110",
//         "LAN8070",
//         "KAL7968",
//         "FIN4424"
//       ],
//       "codeshares_iata": [
//         "JL5512",
//         "CA7110",
//         "LA8070",
//         "KE7968",
//         "AY4424"
//       ],
//       "blocked": false,
//       "diverted": false,
//       "cancelled": false,
//       "position_only": false,
//       "origin": {
//         "code": "SBGR",
//         "code_icao": "SBGR",
//         "code_iata": "GRU",
//         "code_lid": null,
//         "timezone": "America/Sao_Paulo",
//         "name": "São Paulo-Guarulhos Int'l",
//         "city": "Sao Paulo",
//         "airport_info_url": "/airports/SBGR"
//       },
//       "destination": {
//         "code": "EDDF",
//         "code_icao": "EDDF",
//         "code_iata": "FRA",
//         "code_lid": null,
//         "timezone": "Europe/Berlin",
//         "name": "Frankfurt Int'l",
//         "city": "Frankfurt am Main",
//         "airport_info_url": "/airports/EDDF"
//       },
//       "departure_delay": 1260,
//       "arrival_delay": -180,
//       "filed_ete": 39720,
//       "foresight_predictions_available": true,
//       "scheduled_out": "2026-04-11T02:45:00Z",
//       "estimated_out": "2026-04-11T02:45:00Z",
//       "actual_out": "2026-04-11T03:06:00Z",
//       "scheduled_off": "2026-04-11T02:55:00Z",
//       "estimated_off": "2026-04-11T03:28:00Z",
//       "actual_off": "2026-04-11T03:34:53Z",
//       "scheduled_on": "2026-04-11T13:57:00Z",
//       "estimated_on": "2026-04-11T14:09:00Z",
//       "actual_on": "2026-04-11T14:09:00Z",
//       "scheduled_in": "2026-04-11T14:25:00Z",
//       "estimated_in": "2026-04-11T14:25:00Z",
//       "actual_in": "2026-04-11T14:22:00Z",
//       "progress_percent": 100,
//       "status": "Arrived / Gate Arrival",
//       "aircraft_type": "B773",
//       "route_distance": 6093,
//       "filed_airspeed": 468,
//       "filed_altitude": null,
//       "route": null,
//       "baggage_claim": null,
//       "seats_cabin_business": null,
//       "seats_cabin_coach": null,
//       "seats_cabin_first": null,
//       "gate_origin": "308",
//       "gate_destination": null,
//       "terminal_origin": "3",
//       "terminal_destination": "1",
//       "type": "Airline"
//     },
//     {
//       "ident": "TAM8070",
//       "ident_icao": "TAM8070",
//       "ident_iata": "JJ8070",
//       "actual_runway_off": "10L",
//       "actual_runway_on": "25L",
//       "fa_flight_id": "TAM8070-1775537431-airline-859p",
//       "operator": "TAM",
//       "operator_icao": "TAM",
//       "operator_iata": "JJ",
//       "flight_number": "8070",
//       "registration": "PT-MUC",
//       "atc_ident": null,
//       "inbound_fa_flight_id": "TAM8121-1775546154-airline-1664p",
//       "codeshares": [
//         "JAL5512",
//         "CCA7110",
//         "LAN8070",
//         "KAL7968",
//         "FIN4424"
//       ],
//       "codeshares_iata": [
//         "JL5512",
//         "CA7110",
//         "LA8070",
//         "KE7968",
//         "AY4424"
//       ],
//       "blocked": false,
//       "diverted": false,
//       "cancelled": false,
//       "position_only": false,
//       "origin": {
//         "code": "SBGR",
//         "code_icao": "SBGR",
//         "code_iata": "GRU",
//         "code_lid": null,
//         "timezone": "America/Sao_Paulo",
//         "name": "São Paulo-Guarulhos Int'l",
//         "city": "Sao Paulo",
//         "airport_info_url": "/airports/SBGR"
//       },
//       "destination": {
//         "code": "EDDF",
//         "code_icao": "EDDF",
//         "code_iata": "FRA",
//         "code_lid": null,
//         "timezone": "Europe/Berlin",
//         "name": "Frankfurt Int'l",
//         "city": "Frankfurt am Main",
//         "airport_info_url": "/airports/EDDF"
//       },
//       "departure_delay": 1920,
//       "arrival_delay": 1800,
//       "filed_ete": 39720,
//       "foresight_predictions_available": true,
//       "scheduled_out": "2026-04-10T02:45:00Z",
//       "estimated_out": "2026-04-10T02:45:00Z",
//       "actual_out": "2026-04-10T03:17:00Z",
//       "scheduled_off": "2026-04-10T02:55:00Z",
//       "estimated_off": "2026-04-10T03:39:00Z",
//       "actual_off": "2026-04-10T03:46:13Z",
//       "scheduled_on": "2026-04-10T13:57:00Z",
//       "estimated_on": "2026-04-10T14:46:01Z",
//       "actual_on": "2026-04-10T14:46:01Z",
//       "scheduled_in": "2026-04-10T14:25:00Z",
//       "estimated_in": "2026-04-10T15:01:00Z",
//       "actual_in": "2026-04-10T14:55:00Z",
//       "progress_percent": 100,
//       "status": "Arrived / Gate Arrival",
//       "aircraft_type": "B773",
//       "route_distance": 6093,
//       "filed_airspeed": 468,
//       "filed_altitude": null,
//       "route": null,
//       "baggage_claim": null,
//       "seats_cabin_business": null,
//       "seats_cabin_coach": null,
//       "seats_cabin_first": null,
//       "gate_origin": "308",
//       "gate_destination": null,
//       "terminal_origin": "3",
//       "terminal_destination": "1",
//       "type": "Airline"
//     },
//     {
//       "ident": "TAM8070",
//       "ident_icao": "TAM8070",
//       "ident_iata": "JJ8070",
//       "actual_runway_off": "28R",
//       "actual_runway_on": "07R",
//       "fa_flight_id": "TAM8070-1775451343-airline-414p",
//       "operator": "TAM",
//       "operator_icao": "TAM",
//       "operator_iata": "JJ",
//       "flight_number": "8070",
//       "registration": "PT-MUG",
//       "atc_ident": null,
//       "inbound_fa_flight_id": "TAM8071-1775364867-airline-1749p",
//       "codeshares": [
//         "JAL5512",
//         "CCA7110",
//         "LAN8070",
//         "KAL7968",
//         "FIN4424"
//       ],
//       "codeshares_iata": [
//         "JL5512",
//         "CA7110",
//         "LA8070",
//         "KE7968",
//         "AY4424"
//       ],
//       "blocked": false,
//       "diverted": false,
//       "cancelled": false,
//       "position_only": false,
//       "origin": {
//         "code": "SBGR",
//         "code_icao": "SBGR",
//         "code_iata": "GRU",
//         "code_lid": null,
//         "timezone": "America/Sao_Paulo",
//         "name": "São Paulo-Guarulhos Int'l",
//         "city": "Sao Paulo",
//         "airport_info_url": "/airports/SBGR"
//       },
//       "destination": {
//         "code": "EDDF",
//         "code_icao": "EDDF",
//         "code_iata": "FRA",
//         "code_lid": null,
//         "timezone": "Europe/Berlin",
//         "name": "Frankfurt Int'l",
//         "city": "Frankfurt am Main",
//         "airport_info_url": "/airports/EDDF"
//       },
//       "departure_delay": 0,
//       "arrival_delay": 660,
//       "filed_ete": 39720,
//       "foresight_predictions_available": true,
//       "scheduled_out": "2026-04-09T02:45:00Z",
//       "estimated_out": "2026-04-09T02:45:00Z",
//       "actual_out": "2026-04-09T02:45:00Z",
//       "scheduled_off": "2026-04-09T02:55:00Z",
//       "estimated_off": "2026-04-09T03:10:28Z",
//       "actual_off": "2026-04-09T03:10:28Z",
//       "scheduled_on": "2026-04-09T13:57:00Z",
//       "estimated_on": "2026-04-09T14:28:08Z",
//       "actual_on": "2026-04-09T14:28:08Z",
//       "scheduled_in": "2026-04-09T14:25:00Z",
//       "estimated_in": "2026-04-09T14:43:00Z",
//       "actual_in": "2026-04-09T14:36:00Z",
//       "progress_percent": 100,
//       "status": "Arrived / Gate Arrival",
//       "aircraft_type": "B773",
//       "route_distance": 6093,
//       "filed_airspeed": 468,
//       "filed_altitude": null,
//       "route": null,
//       "baggage_claim": null,
//       "seats_cabin_business": null,
//       "seats_cabin_coach": null,
//       "seats_cabin_first": null,
//       "gate_origin": "322",
//       "gate_destination": null,
//       "terminal_origin": "3",
//       "terminal_destination": "1",
//       "type": "Airline"
//     },
//     {
//       "ident": "TAM8070",
//       "ident_icao": "TAM8070",
//       "ident_iata": "JJ8070",
//       "actual_runway_off": "10L",
//       "actual_runway_on": "07L",
//       "fa_flight_id": "TAM8070-1775364867-airline-1751p",
//       "operator": "TAM",
//       "operator_icao": "TAM",
//       "operator_iata": "JJ",
//       "flight_number": "8070",
//       "registration": "PT-MUI",
//       "atc_ident": null,
//       "inbound_fa_flight_id": "TAM8121-1775364901-airline-767p",
//       "codeshares": [
//         "JAL5512",
//         "CCA7110",
//         "LAN8070",
//         "KAL7968",
//         "FIN4424"
//       ],
//       "codeshares_iata": [
//         "JL5512",
//         "CA7110",
//         "LA8070",
//         "KE7968",
//         "AY4424"
//       ],
//       "blocked": false,
//       "diverted": false,
//       "cancelled": false,
//       "position_only": false,
//       "origin": {
//         "code": "SBGR",
//         "code_icao": "SBGR",
//         "code_iata": "GRU",
//         "code_lid": null,
//         "timezone": "America/Sao_Paulo",
//         "name": "São Paulo-Guarulhos Int'l",
//         "city": "Sao Paulo",
//         "airport_info_url": "/airports/SBGR"
//       },
//       "destination": {
//         "code": "EDDF",
//         "code_icao": "EDDF",
//         "code_iata": "FRA",
//         "code_lid": null,
//         "timezone": "Europe/Berlin",
//         "name": "Frankfurt Int'l",
//         "city": "Frankfurt am Main",
//         "airport_info_url": "/airports/EDDF"
//       },
//       "departure_delay": 360,
//       "arrival_delay": 840,
//       "filed_ete": 39720,
//       "foresight_predictions_available": true,
//       "scheduled_out": "2026-04-08T02:45:00Z",
//       "estimated_out": "2026-04-08T02:45:00Z",
//       "actual_out": "2026-04-08T02:51:00Z",
//       "scheduled_off": "2026-04-08T02:55:00Z",
//       "estimated_off": "2026-04-08T03:13:00Z",
//       "actual_off": "2026-04-08T03:27:05Z",
//       "scheduled_on": "2026-04-08T13:57:00Z",
//       "estimated_on": "2026-04-08T14:22:18Z",
//       "actual_on": "2026-04-08T14:22:18Z",
//       "scheduled_in": "2026-04-08T14:25:00Z",
//       "estimated_in": "2026-04-08T14:37:00Z",
//       "actual_in": "2026-04-08T14:39:00Z",
//       "progress_percent": 100,
//       "status": "Arrived / Gate Arrival",
//       "aircraft_type": "B773",
//       "route_distance": 6093,
//       "filed_airspeed": 468,
//       "filed_altitude": null,
//       "route": null,
//       "baggage_claim": null,
//       "seats_cabin_business": null,
//       "seats_cabin_coach": null,
//       "seats_cabin_first": null,
//       "gate_origin": "332",
//       "gate_destination": null,
//       "terminal_origin": "3",
//       "terminal_destination": "1",
//       "type": "Airline"
//     },
//     {
//       "ident": "TAM8070",
//       "ident_icao": "TAM8070",
//       "ident_iata": "JJ8070",
//       "actual_runway_off": "10L",
//       "actual_runway_on": "07L",
//       "fa_flight_id": "TAM8070-1775282061-airline-679p",
//       "operator": "TAM",
//       "operator_icao": "TAM",
//       "operator_iata": "JJ",
//       "flight_number": "8070",
//       "registration": "PT-MUG",
//       "atc_ident": null,
//       "inbound_fa_flight_id": "TAM8121-1775286827-airline-1335p",
//       "codeshares": [
//         "JAL5512",
//         "CCA7110",
//         "LAN8070",
//         "KAL7968",
//         "FIN4424"
//       ],
//       "codeshares_iata": [
//         "JL5512",
//         "CA7110",
//         "LA8070",
//         "KE7968",
//         "AY4424"
//       ],
//       "blocked": false,
//       "diverted": false,
//       "cancelled": false,
//       "position_only": false,
//       "origin": {
//         "code": "SBGR",
//         "code_icao": "SBGR",
//         "code_iata": "GRU",
//         "code_lid": null,
//         "timezone": "America/Sao_Paulo",
//         "name": "São Paulo-Guarulhos Int'l",
//         "city": "Sao Paulo",
//         "airport_info_url": "/airports/SBGR"
//       },
//       "destination": {
//         "code": "EDDF",
//         "code_icao": "EDDF",
//         "code_iata": "FRA",
//         "code_lid": null,
//         "timezone": "Europe/Berlin",
//         "name": "Frankfurt Int'l",
//         "city": "Frankfurt am Main",
//         "airport_info_url": "/airports/EDDF"
//       },
//       "departure_delay": -180,
//       "arrival_delay": 0,
//       "filed_ete": 39720,
//       "foresight_predictions_available": true,
//       "scheduled_out": "2026-04-07T02:45:00Z",
//       "estimated_out": "2026-04-07T02:45:00Z",
//       "actual_out": "2026-04-07T02:42:00Z",
//       "scheduled_off": "2026-04-07T02:55:00Z",
//       "estimated_off": "2026-04-07T03:04:00Z",
//       "actual_off": "2026-04-07T03:19:23Z",
//       "scheduled_on": "2026-04-07T13:57:00Z",
//       "estimated_on": "2026-04-07T14:13:59Z",
//       "actual_on": "2026-04-07T14:13:59Z",
//       "scheduled_in": "2026-04-07T14:25:00Z",
//       "estimated_in": "2026-04-07T14:29:00Z",
//       "actual_in": "2026-04-07T14:25:00Z",
//       "progress_percent": 100,
//       "status": "Arrived / Gate Arrival",
//       "aircraft_type": "B773",
//       "route_distance": 6093,
//       "filed_airspeed": 468,
//       "filed_altitude": null,
//       "route": null,
//       "baggage_claim": null,
//       "seats_cabin_business": null,
//       "seats_cabin_coach": null,
//       "seats_cabin_first": null,
//       "gate_origin": "330",
//       "gate_destination": null,
//       "terminal_origin": "3",
//       "terminal_destination": "1",
//       "type": "Airline"
//     },
//     {
//       "ident": "TAM8070",
//       "ident_icao": "TAM8070",
//       "ident_iata": "JJ8070",
//       "actual_runway_off": "10L",
//       "actual_runway_on": "25R",
//       "fa_flight_id": "TAM8070-1775192061-airline-2483p",
//       "operator": "TAM",
//       "operator_icao": "TAM",
//       "operator_iata": "JJ",
//       "flight_number": "8070",
//       "registration": "PT-MUH",
//       "atc_ident": null,
//       "inbound_fa_flight_id": "TAM8121-1775199809-airline-1337p",
//       "codeshares": [
//         "JAL5512",
//         "CCA7110",
//         "LAN8070",
//         "KAL7968",
//         "FIN4424"
//       ],
//       "codeshares_iata": [
//         "JL5512",
//         "CA7110",
//         "LA8070",
//         "KE7968",
//         "AY4424"
//       ],
//       "blocked": false,
//       "diverted": false,
//       "cancelled": false,
//       "position_only": false,
//       "origin": {
//         "code": "SBGR",
//         "code_icao": "SBGR",
//         "code_iata": "GRU",
//         "code_lid": null,
//         "timezone": "America/Sao_Paulo",
//         "name": "São Paulo-Guarulhos Int'l",
//         "city": "Sao Paulo",
//         "airport_info_url": "/airports/SBGR"
//       },
//       "destination": {
//         "code": "EDDF",
//         "code_icao": "EDDF",
//         "code_iata": "FRA",
//         "code_lid": null,
//         "timezone": "Europe/Berlin",
//         "name": "Frankfurt Int'l",
//         "city": "Frankfurt am Main",
//         "airport_info_url": "/airports/EDDF"
//       },
//       "departure_delay": 2580,
//       "arrival_delay": 1500,
//       "filed_ete": 39540,
//       "foresight_predictions_available": true,
//       "scheduled_out": "2026-04-06T02:45:00Z",
//       "estimated_out": "2026-04-06T03:30:00Z",
//       "actual_out": "2026-04-06T03:28:00Z",
//       "scheduled_off": "2026-04-06T02:55:00Z",
//       "estimated_off": "2026-04-06T03:50:00Z",
//       "actual_off": "2026-04-06T03:45:38Z",
//       "scheduled_on": "2026-04-06T13:54:00Z",
//       "estimated_on": "2026-04-06T14:38:23Z",
//       "actual_on": "2026-04-06T14:38:23Z",
//       "scheduled_in": "2026-04-06T14:25:00Z",
//       "estimated_in": "2026-04-06T14:53:00Z",
//       "actual_in": "2026-04-06T14:50:00Z",
//       "progress_percent": 100,
//       "status": "Arrived / Gate Arrival",
//       "aircraft_type": "B773",
//       "route_distance": 6093,
//       "filed_airspeed": 468,
//       "filed_altitude": null,
//       "route": null,
//       "baggage_claim": null,
//       "seats_cabin_business": null,
//       "seats_cabin_coach": null,
//       "seats_cabin_first": null,
//       "gate_origin": "310",
//       "gate_destination": null,
//       "terminal_origin": "3",
//       "terminal_destination": "1",
//       "type": "Airline"
//     },
//     {
//       "ident": "TAM8070",
//       "ident_icao": "TAM8070",
//       "ident_iata": "JJ8070",
//       "actual_runway_off": "10L",
//       "actual_runway_on": "25R",
//       "fa_flight_id": "TAM8070-1775108070-airline-1060p",
//       "operator": "TAM",
//       "operator_icao": "TAM",
//       "operator_iata": "JJ",
//       "flight_number": "8070",
//       "registration": "PT-MUI",
//       "atc_ident": null,
//       "inbound_fa_flight_id": "TAM8073-1775108070-airline-1063p",
//       "codeshares": [
//         "JAL5512",
//         "CCA7110",
//         "LAN8070",
//         "KAL7968",
//         "FIN4424"
//       ],
//       "codeshares_iata": [
//         "JL5512",
//         "CA7110",
//         "LA8070",
//         "KE7968",
//         "AY4424"
//       ],
//       "blocked": false,
//       "diverted": false,
//       "cancelled": false,
//       "position_only": false,
//       "origin": {
//         "code": "SBGR",
//         "code_icao": "SBGR",
//         "code_iata": "GRU",
//         "code_lid": null,
//         "timezone": "America/Sao_Paulo",
//         "name": "São Paulo-Guarulhos Int'l",
//         "city": "Sao Paulo",
//         "airport_info_url": "/airports/SBGR"
//       },
//       "destination": {
//         "code": "EDDF",
//         "code_icao": "EDDF",
//         "code_iata": "FRA",
//         "code_lid": null,
//         "timezone": "Europe/Berlin",
//         "name": "Frankfurt Int'l",
//         "city": "Frankfurt am Main",
//         "airport_info_url": "/airports/EDDF"
//       },
//       "departure_delay": -540,
//       "arrival_delay": -1860,
//       "filed_ete": 39720,
//       "foresight_predictions_available": true,
//       "scheduled_out": "2026-04-05T02:45:00Z",
//       "estimated_out": "2026-04-05T02:45:00Z",
//       "actual_out": "2026-04-05T02:36:00Z",
//       "scheduled_off": "2026-04-05T02:55:00Z",
//       "estimated_off": "2026-04-05T02:58:00Z",
//       "actual_off": "2026-04-05T02:51:54Z",
//       "scheduled_on": "2026-04-05T13:57:00Z",
//       "estimated_on": "2026-04-05T13:41:49Z",
//       "actual_on": "2026-04-05T13:41:49Z",
//       "scheduled_in": "2026-04-05T14:25:00Z",
//       "estimated_in": "2026-04-05T13:57:00Z",
//       "actual_in": "2026-04-05T13:54:00Z",
//       "progress_percent": 100,
//       "status": "Arrived / Gate Arrival",
//       "aircraft_type": "B773",
//       "route_distance": 6093,
//       "filed_airspeed": 468,
//       "filed_altitude": null,
//       "route": null,
//       "baggage_claim": null,
//       "seats_cabin_business": null,
//       "seats_cabin_coach": null,
//       "seats_cabin_first": null,
//       "gate_origin": "328",
//       "gate_destination": null,
//       "terminal_origin": "3",
//       "terminal_destination": "1",
//       "type": "Airline"
//     },
//     {
//       "ident": "TAM8070",
//       "ident_icao": "TAM8070",
//       "ident_iata": "JJ8070",
//       "actual_runway_off": "10L",
//       "actual_runway_on": "25R",
//       "fa_flight_id": "TAM8070-1775019318-airline-1233p",
//       "operator": "TAM",
//       "operator_icao": "TAM",
//       "operator_iata": "JJ",
//       "flight_number": "8070",
//       "registration": "PT-MUF",
//       "atc_ident": null,
//       "inbound_fa_flight_id": "TAM8115-1775022395-airline-153p",
//       "codeshares": [
//         "JAL5512",
//         "CCA7110",
//         "LAN8070",
//         "KAL7968",
//         "FIN4424"
//       ],
//       "codeshares_iata": [
//         "JL5512",
//         "CA7110",
//         "LA8070",
//         "KE7968",
//         "AY4424"
//       ],
//       "blocked": false,
//       "diverted": false,
//       "cancelled": false,
//       "position_only": false,
//       "origin": {
//         "code": "SBGR",
//         "code_icao": "SBGR",
//         "code_iata": "GRU",
//         "code_lid": null,
//         "timezone": "America/Sao_Paulo",
//         "name": "São Paulo-Guarulhos Int'l",
//         "city": "Sao Paulo",
//         "airport_info_url": "/airports/SBGR"
//       },
//       "destination": {
//         "code": "EDDF",
//         "code_icao": "EDDF",
//         "code_iata": "FRA",
//         "code_lid": null,
//         "timezone": "Europe/Berlin",
//         "name": "Frankfurt Int'l",
//         "city": "Frankfurt am Main",
//         "airport_info_url": "/airports/EDDF"
//       },
//       "departure_delay": 1020,
//       "arrival_delay": 720,
//       "filed_ete": 39720,
//       "foresight_predictions_available": true,
//       "scheduled_out": "2026-04-04T02:45:00Z",
//       "estimated_out": "2026-04-04T02:45:00Z",
//       "actual_out": "2026-04-04T03:02:00Z",
//       "scheduled_off": "2026-04-04T02:55:00Z",
//       "estimated_off": "2026-04-04T03:24:00Z",
//       "actual_off": "2026-04-04T03:27:34Z",
//       "scheduled_on": "2026-04-04T13:57:00Z",
//       "estimated_on": "2026-04-04T14:22:20Z",
//       "actual_on": "2026-04-04T14:22:20Z",
//       "scheduled_in": "2026-04-04T14:25:00Z",
//       "estimated_in": "2026-04-04T14:37:00Z",
//       "actual_in": "2026-04-04T14:37:00Z",
//       "progress_percent": 100,
//       "status": "Arrived / Gate Arrival",
//       "aircraft_type": "B773",
//       "route_distance": 6093,
//       "filed_airspeed": 468,
//       "filed_altitude": null,
//       "route": null,
//       "baggage_claim": null,
//       "seats_cabin_business": null,
//       "seats_cabin_coach": null,
//       "seats_cabin_first": null,
//       "gate_origin": "322",
//       "gate_destination": null,
//       "terminal_origin": "3",
//       "terminal_destination": "1",
//       "type": "Airline"
//     },
//     {
//       "ident": "TAM8070",
//       "ident_icao": "TAM8070",
//       "ident_iata": "JJ8070",
//       "actual_runway_off": "10L",
//       "actual_runway_on": "25L",
//       "fa_flight_id": "TAM8070-1774932970-airline-1891p",
//       "operator": "TAM",
//       "operator_icao": "TAM",
//       "operator_iata": "JJ",
//       "flight_number": "8070",
//       "registration": "PT-MUB",
//       "atc_ident": null,
//       "inbound_fa_flight_id": "TAM8121-1774941243-airline-1596p",
//       "codeshares": [
//         "JAL5512",
//         "CCA7110",
//         "LAN8070",
//         "KAL7968",
//         "FIN4424"
//       ],
//       "codeshares_iata": [
//         "JL5512",
//         "CA7110",
//         "LA8070",
//         "KE7968",
//         "AY4424"
//       ],
//       "blocked": false,
//       "diverted": false,
//       "cancelled": false,
//       "position_only": false,
//       "origin": {
//         "code": "SBGR",
//         "code_icao": "SBGR",
//         "code_iata": "GRU",
//         "code_lid": null,
//         "timezone": "America/Sao_Paulo",
//         "name": "São Paulo-Guarulhos Int'l",
//         "city": "Sao Paulo",
//         "airport_info_url": "/airports/SBGR"
//       },
//       "destination": {
//         "code": "EDDF",
//         "code_icao": "EDDF",
//         "code_iata": "FRA",
//         "code_lid": null,
//         "timezone": "Europe/Berlin",
//         "name": "Frankfurt Int'l",
//         "city": "Frankfurt am Main",
//         "airport_info_url": "/airports/EDDF"
//       },
//       "departure_delay": 900,
//       "arrival_delay": 1020,
//       "filed_ete": 39720,
//       "foresight_predictions_available": true,
//       "scheduled_out": "2026-04-03T02:45:00Z",
//       "estimated_out": "2026-04-03T02:45:00Z",
//       "actual_out": "2026-04-03T03:00:00Z",
//       "scheduled_off": "2026-04-03T02:55:00Z",
//       "estimated_off": "2026-04-03T03:22:00Z",
//       "actual_off": "2026-04-03T03:24:14Z",
//       "scheduled_on": "2026-04-03T13:57:00Z",
//       "estimated_on": "2026-04-03T14:32:25Z",
//       "actual_on": "2026-04-03T14:32:25Z",
//       "scheduled_in": "2026-04-03T14:25:00Z",
//       "estimated_in": "2026-04-03T14:48:00Z",
//       "actual_in": "2026-04-03T14:42:00Z",
//       "progress_percent": 100,
//       "status": "Arrived / Gate Arrival",
//       "aircraft_type": "B773",
//       "route_distance": 6093,
//       "filed_airspeed": 468,
//       "filed_altitude": null,
//       "route": null,
//       "baggage_claim": "13",
//       "seats_cabin_business": null,
//       "seats_cabin_coach": null,
//       "seats_cabin_first": null,
//       "gate_origin": "322",
//       "gate_destination": null,
//       "terminal_origin": "3",
//       "terminal_destination": "1",
//       "type": "Airline"
//     },
//     {
//       "ident": "TAM8070",
//       "ident_icao": "TAM8070",
//       "ident_iata": "JJ8070",
//       "actual_runway_off": "10L",
//       "actual_runway_on": "25L",
//       "fa_flight_id": "TAM8070-1774848444-airline-1203p",
//       "operator": "TAM",
//       "operator_icao": "TAM",
//       "operator_iata": "JJ",
//       "flight_number": "8070",
//       "registration": "PT-MUJ",
//       "atc_ident": null,
//       "inbound_fa_flight_id": "TAM8121-1774854544-airline-1088p",
//       "codeshares": [
//         "JAL5512",
//         "CCA7110",
//         "LAN8070",
//         "KAL7968",
//         "FIN4424"
//       ],
//       "codeshares_iata": [
//         "JL5512",
//         "CA7110",
//         "LA8070",
//         "KE7968",
//         "AY4424"
//       ],
//       "blocked": false,
//       "diverted": false,
//       "cancelled": false,
//       "position_only": false,
//       "origin": {
//         "code": "SBGR",
//         "code_icao": "SBGR",
//         "code_iata": "GRU",
//         "code_lid": null,
//         "timezone": "America/Sao_Paulo",
//         "name": "São Paulo-Guarulhos Int'l",
//         "city": "Sao Paulo",
//         "airport_info_url": "/airports/SBGR"
//       },
//       "destination": {
//         "code": "EDDF",
//         "code_icao": "EDDF",
//         "code_iata": "FRA",
//         "code_lid": null,
//         "timezone": "Europe/Berlin",
//         "name": "Frankfurt Int'l",
//         "city": "Frankfurt am Main",
//         "airport_info_url": "/airports/EDDF"
//       },
//       "departure_delay": 2400,
//       "arrival_delay": 3060,
//       "filed_ete": 39720,
//       "foresight_predictions_available": true,
//       "scheduled_out": "2026-04-02T02:45:00Z",
//       "estimated_out": "2026-04-02T02:45:00Z",
//       "actual_out": "2026-04-02T03:25:00Z",
//       "scheduled_off": "2026-04-02T02:55:00Z",
//       "estimated_off": "2026-04-02T03:54:23Z",
//       "actual_off": "2026-04-02T03:54:23Z",
//       "scheduled_on": "2026-04-02T13:57:00Z",
//       "estimated_on": "2026-04-02T15:04:10Z",
//       "actual_on": "2026-04-02T15:04:10Z",
//       "scheduled_in": "2026-04-02T14:25:00Z",
//       "estimated_in": "2026-04-02T15:19:00Z",
//       "actual_in": "2026-04-02T15:16:00Z",
//       "progress_percent": 100,
//       "status": "Arrived / Delayed",
//       "aircraft_type": "B773",
//       "route_distance": 6093,
//       "filed_airspeed": 468,
//       "filed_altitude": null,
//       "route": null,
//       "baggage_claim": "13",
//       "seats_cabin_business": null,
//       "seats_cabin_coach": null,
//       "seats_cabin_first": null,
//       "gate_origin": "304",
//       "gate_destination": null,
//       "terminal_origin": "3",
//       "terminal_destination": "1",
//       "type": "Airline"
//     }
//   ],
//   "links": null,
//   "num_pages": 1
// }

// Error
// {
//   "title": "Invalid API key",
//   "reason": "INVALID_API_KEY",
//   "detail": "Provided API key is not valid",
//   "status": 401
// }